### PR TITLE
fix opcache reset for php version > 5.5

### PR DESCRIPTION
**Pull request by amine26tz**
this PR let the bundle extension check apc extension only for PHP version superior to 5.5.0

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
What is the advantage of this? `function_exists` does the job well as is.

**Comment by amine26tz** [comment]
@Soullivaneuh  the ApcCache handle now the opcode and apc cache with same bundle configuration see https://github.com/sonata-project/cache/commit/f2f6be96c270d6a2b1f26fdc1d6edcb586b60691. we should check apc function exists only for php version that doesn't support opcode cache.

**Comment by amine26tz** [comment]
@Soullivaneuh, i ve updated this PR to allow Apc cacheAction to reset opcache for php version > 5.5. ping @rande

**Comment by amine26tz** [comment]
ping @rande

**Pull request merged**
