### PR TITLE
Allow Support PHP 8.0

### PR DESCRIPTION
**Pull request by Yozhef**
## Changelog

```markdown
### Added
- Add support for PHP 8.0
```

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Thanks @Yozhef ; If you want to help, can you do also the PR on dev-kit.

It's similar to https://github.com/sonata-project/dev-kit/pull/1368

**Comment by Yozhef** [comment]
@VincentLanglet yes, sure

**Comment by Yozhef** [comment]
@VincentLanglet done https://github.com/sonata-project/dev-kit/pull/1370

**Pull request merged**
