### PR TITLE
Add Symfony 6 support

### PR DESCRIPTION
**Pull request by jordisala1991**
## Subject

I am targeting this branch, because this is BC.

Part of: https://github.com/sonata-project/dev-kit/issues/1675
Dev-kit PR: https://github.com/sonata-project/dev-kit/pull/1816

## Changelog

```markdown
### Added
- Added support for Symfony 6.
### Removed
- Removed support for Symfony 5.2.
- Removed support for PHP < 7.3.
```

### CODE REVIEW

**Comment by jordisala1991** [comment]
Blocked by: doctrine/phpcr-odm

**Comment by VincentLanglet** [comment]
> doctrine/phpcr-odm

They only use symfony/console and symfony/yaml, maybe the PR could be easy.
If not, we might consider adding the support to at least not block orm or mongo.

**Comment by VincentLanglet** [comment]
Waiting for https://github.com/doctrine/phpcr-odm/pull/822

**Comment by VincentLanglet** [comment]
Since this package is deprecated, this might be not worthy to add SF6 @jordisala1991

**Comment by dbu** [comment]
phpcr-odm symfony 6 support is tagged as https://github.com/doctrine/phpcr-odm/releases/tag/1.6.0

**Comment by jordisala1991** [comment]
> Since this package is deprecated, this might be not worthy to add SF6 @jordisala1991

Since it is that easy to add support I think it is better to add it to not have blockers for PageBundle.

**Review by VincentLanglet — APPROVED** [review]

**Review by core23 — APPROVED** [review]

**Pull request merged**
