### PR TITLE
Symfony 2.7 BC break fix

### PR DESCRIPTION
**Pull request by linasm83**
See issue #72 for more details

### CODE REVIEW

**Comment by rande** [comment]
@linasm83 can you just check the method is available with symfony2.3 or the minimun requirements for the twig version ? Thanks

**Comment by linasm83** [comment]
@rande as I see the method *[getBaseTemplateClass](https://github.com/twigphp/Twig/blob/v1.0.0/lib/Twig/Environment.php#L118)* on *Twig_Environment* exists from the start of twig version 1, so shouldn't be a problem there

**Comment by richardfullmer** [comment]
Incomming tag?

**Comment by gnutix** [comment]
Waiting on the tag as well. :)

**Comment by Soullivaneuh** [comment]
@rande a minor tag version should be push as priority since SF 2.7 is not stable.

**Comment by Soullivaneuh** [comment]
@richardfullmer @gnutix done: https://github.com/sonata-project/SonataCacheBundle/releases/tag/2.2.3

**Pull request merged**
