### PR TITLE
Added parameters to xml service definitions

### PR DESCRIPTION
**Pull request by spolischook**
To redefine and inherit some service, I need to opportunity to redefine service namespace

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
This is not recommended by SF best practices anymore.

@spolischook What is exactly your need?

ping @rande

**Comment by spolischook** [comment]
In case when you need redefine service it would be great to have parameter to redefine class of service

**Comment by Soullivaneuh** [comment]
> This practice was wrongly adopted from third-party bundles. When Symfony introduced its service container, some developers used this technique to easily allow overriding services. However, overriding a service by just changing its class name is a very rare use case because, frequently, the new service has different constructor arguments.

From: http://symfony.com/doc/current/best_practices/business-logic.html

Maybe we could find another solution like service tag and configuration. FOSUser does on this way AFAIK.

@rande what do you think?

**Comment by spolischook** [comment]
This rule for your AppBundle not for third-party bundles, like SonataCacheBundle.
> This practice is cumbersome and completely unnecessary for **your own services**
So this is exactly that recommends by symfony community,

**Comment by Soullivaneuh** [comment]
I'm not sure of that because of this:

> This practice was **wrongly** adopted from **third-party bundles**.

Weeks ago, I did a PR with a new service and @stof recommended me to not use class parameter.

He could maybe give us a better explanation. :-)

BTW you didn't give me exactly your need. Could you give me a sample of your class that should replace the default one?

For this case, maybe add an independent `CustomCache` service to be integrated on this bundle would be a better way. Don't know if it's possible now with actual configuration.

Another solution like FOS that could be applied: https://github.com/FriendsOfSymfony/FOSUserBundle/blob/master/Resources/doc/overriding_forms.md

**Comment by rande** [comment]
The idea is that just changing the class name is not enough, you also want to change the constructor signature. So using class parameter cannot be used to change the constructor. That is why they get removed from Symfony's bundles.

**Comment by spolischook** [comment]
SonataCacheBundle is a third-party bundle so this approach is about it.
@rande if I need to redefine only one method now I need redefine all service

However this PR is not so actual because I don't remember what I do 1 year ago in our project, so you can close it if you need

**Comment by Soullivaneuh** [comment]
> SonataCacheBundle is a third-party bundle so this approach is about it.

This is especially not the good approach by Symfony convention, see my last quote.

> I don't remember what I do 1 year ago in our project, so you can close it if you need

Ok for that, however, thinking of the possibility to add custom cache services could be a good idea, if it is not already done. @rande?

**Pull request closed without merging**
