### PR TITLE
Allow predis 1

### PR DESCRIPTION
**Pull request by greg0ire**
I am targetting this branch, because this is BC.

Refs https://github.com/sonata-project/dev-kit/issues/216

This is pedantic because it's only about a development dependency.

### CODE REVIEW

**Comment by OskarStark** [comment]
@greg0ire can you restart StyleCi by push --force?

**Comment by greg0ire** [comment]
Works great :)

**Comment by greg0ire** [comment]
@sonata-project/contributors please review

**Comment by core23** [comment]
Don't know the `predis` dep. So I can't say anything here

**Comment by greg0ire** [comment]
I don't know it either :/ Just blindly merge here please…

**Pull request merged**
